agent:
  step_limit: 250
  cost_limit: 0.0

environment:
  timeout: 120
  run_args:
    - --rm
    - --memory=4g

model:
  model_class: litellm_textbased
  cost_tracking: ignore_errors
  model_kwargs:
    drop_params: true
